# baseURL: 'https://micro-ressort.be/'
baseURL: '/'
languageCode: 'fr'
title: 'Micro-ressort'
theme: "micro-ressort"
relativeURLS: true
googleAnalytics: "G-LTV96GR4EE"
params:
  description: Sollicitez un appui financier et social pour votre projet de vie
  url: https://micro-ressort.be/
  google_fonts:
  - [
    Dosis,
    "400, 700"
  ]
  - [
    Roboto,
    "400, 400i, 500, 500i, 700, 700i"
  ]
  heading_font: "Fira Code"
  body_font: "Open Sans"
