baseURL = "http://example.org/"
languageCode = "en-us"
title = "Micro-ressort"
theme = "micro-ressort"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
