name = "Micro-ressort"
license = "Unlicense"
licenselink = "https://unlicense.org"
description = "Minimalist Hugo theme with a penchant for accessibility"
tags = ["minimalist", "accessible", "simple"]
features = ["For visually impaired readers and developers"]
min_version = "0.1"

[author]
  name = "Leon Stafford"
  homepage = "https://ljs.dev"

